name: Build

on:
  push:
    paths-ignore:
    - README.md

jobs:
  build:
    name: ${{ matrix.os }} with ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [2.7, 3.6, 3.7, 3.8]
    steps:
    - name: Print Python version
      run: python -V
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Run the script
      run: ./scripta.py
